add k8s cluster deployment
microservices-demo/microservices-demo.github.io pull request #63
Opened 2017-05-30 14:41 UTC by dtzar

Allows people to deploy the base socks shop to any kubernetes cluster (no provider-lock-in) like currently exists with the terraform deployment choice.

2017-06-06 09:12 UTC, pidster requested changes
Did you intend to change the URL of "Any Kubernetes Cluster" to `.../kubernetes-start.html`?

2017-06-06 15:13 UTC, dtzar commented
Yes, thanks for the catch.  I resolved this.

2017-06-07 14:27 UTC, pidster approved these changes

2017-06-07 14:27 UTC, merged

2017-06-08 21:45 UTC, dtzar commented
Unfortunately @pidster It looks like the [new link created from this PR](https://microservices-demo.github.io/microservices-demo/deployment/kubernetes-start.html) doesn't work :(.  the nav url matches what is in the md file.  Is there some other file which I need to modify so the md gets rendered into html?

2017-06-12 10:04 UTC, pidster commented
Good catch & fixed. There's a submodule & another repo that needed pushing too...